import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { rateLimit, getClientIp } from "@/lib/rateLimit";
import { getResend } from "@/lib/email";
import { emailFooter } from "@/lib/email/footer";

export const runtime = "nodejs";

const VALID_ROLES = new Set([
  "Backend Engineer",
  "Fintech Engineer",
  "Security Engineer",
  "Customer Support",
  "Trust & Safety",
  "Payments Operations",
]);

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PHONE_RE = /^[\d\s\+\-\(\)\.]{7,30}$/;

export async function POST(req: NextRequest) {
  const ip = getClientIp(req);

  const { allowed } = await rateLimit(`careers-apply:${ip}`, 3, 3600);
  if (!allowed) {
    return NextResponse.json(
      { error: "Too many submissions. Please try again later." },
      { status: 429 }
    );
  }

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const {
    name, email, phone,
    authorized, sponsorship,
    role, salary, start_date,
    years, experience, system, why,
    felony, felony_explain,
    portfolio, linkedin,
    references,
    school, degree, discipline,
    additional_profiles, why_role, company_mission,
    previously_employed, employment_dates, contract_work, contract_details,
    resume_url, cover_letter_url,
    agree,
  } = body;

  // ── Required field presence ──────────────────────────────────────────────
  const missing = [
    !name || typeof name !== "string" || !(name as string).trim(),
    !email || typeof email !== "string" || !(email as string).trim(),
    !phone || typeof phone !== "string" || !(phone as string).trim(),
    !authorized || typeof authorized !== "string",
    !sponsorship || typeof sponsorship !== "string",
    !role || typeof role !== "string" || !(role as string).trim(),
    !experience || typeof experience !== "string" || !(experience as string).trim(),
    !system || typeof system !== "string" || !(system as string).trim(),
    !why || typeof why !== "string" || !(why as string).trim(),
    !why_role || typeof why_role !== "string" || !(why_role as string).trim(),
    !company_mission || typeof company_mission !== "string" || !(company_mission as string).trim(),
    !felony || typeof felony !== "string",
    agree !== true,
    // Resume is required
    !resume_url || typeof resume_url !== "string" || !(resume_url as string).trim(),
  ].some(Boolean);

  if (missing) {
    return NextResponse.json(
      { error: "Please fill in all required fields and accept the certification." },
      { status: 422 }
    );
  }

  // File path format validation (must be UUID.ext — generated by /api/careers/upload)
  const FILE_PATH_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(pdf|doc|docx)$/i;
  if (!FILE_PATH_RE.test((resume_url as string).trim())) {
    return NextResponse.json({ error: "Invalid resume file." }, { status: 422 });
  }
  if (typeof cover_letter_url === "string" && cover_letter_url.trim() &&
      !FILE_PATH_RE.test(cover_letter_url.trim())) {
    return NextResponse.json({ error: "Invalid cover letter file." }, { status: 422 });
  }

  // ── Format validation ────────────────────────────────────────────────────
  if (!EMAIL_RE.test((email as string).trim())) {
    return NextResponse.json({ error: "Please enter a valid email address." }, { status: 422 });
  }
  if (!PHONE_RE.test((phone as string).trim())) {
    return NextResponse.json({ error: "Please enter a valid phone number." }, { status: 422 });
  }
  if (!VALID_ROLES.has((role as string).trim())) {
    return NextResponse.json({ error: "Invalid role selected." }, { status: 422 });
  }
  if (!["yes", "no"].includes((authorized as string).trim())) {
    return NextResponse.json({ error: "Invalid work authorization value." }, { status: 422 });
  }
  if (!["yes", "no"].includes((sponsorship as string).trim())) {
    return NextResponse.json({ error: "Invalid sponsorship value." }, { status: 422 });
  }
  if (!["yes", "no"].includes((felony as string).trim())) {
    return NextResponse.json({ error: "Invalid background disclosure value." }, { status: 422 });
  }
  if (typeof previously_employed === "string" && previously_employed.trim() &&
      !["yes", "no"].includes(previously_employed.trim())) {
    return NextResponse.json({ error: "Invalid previous employment value." }, { status: 422 });
  }
  if (typeof contract_work === "string" && contract_work.trim() &&
      !["yes", "no"].includes(contract_work.trim())) {
    return NextResponse.json({ error: "Invalid contract work value." }, { status: 422 });
  }

  // ── Length caps ──────────────────────────────────────────────────────────
  if (
    (name as string).length > 100 ||
    (email as string).length > 200 ||
    (phone as string).length > 30 ||
    (experience as string).length > 3000 ||
    (system as string).length > 3000 ||
    (why as string).length > 2000 ||
    (typeof salary === "string" && (salary as string).length > 80) ||
    (typeof felony_explain === "string" && (felony_explain as string).length > 1000) ||
    (typeof portfolio === "string" && (portfolio as string).length > 300) ||
    (typeof linkedin === "string" && (linkedin as string).length > 300) ||
    (typeof references === "string" && (references as string).length > 2000) ||
    (typeof school === "string" && (school as string).length > 150) ||
    (typeof degree === "string" && (degree as string).length > 100) ||
    (typeof discipline === "string" && (discipline as string).length > 100) ||
    (typeof additional_profiles === "string" && (additional_profiles as string).length > 500) ||
    (typeof why_role === "string" && (why_role as string).length > 2000) ||
    (typeof company_mission === "string" && (company_mission as string).length > 1500) ||
    (typeof employment_dates === "string" && (employment_dates as string).length > 100) ||
    (typeof contract_details === "string" && (contract_details as string).length > 500)
  ) {
    return NextResponse.json(
      { error: "One or more fields exceed the maximum length." },
      { status: 422 }
    );
  }

  // ── URL validation for optional link fields ──────────────────────────────
  const LINK_RE = /^https:\/\/.{3,}/;
  if (typeof portfolio === "string" && portfolio.trim() && !LINK_RE.test(portfolio.trim())) {
    return NextResponse.json({ error: "Portfolio must be a valid https:// URL." }, { status: 422 });
  }
  if (typeof linkedin === "string" && linkedin.trim() && !LINK_RE.test(linkedin.trim())) {
    return NextResponse.json({ error: "LinkedIn URL must be a valid https:// URL." }, { status: 422 });
  }

  // ── Risk detection ───────────────────────────────────────────────────────
  // Run async checks without blocking the response
  const cleanEmail = (email as string).trim().toLowerCase();
  const cleanExp   = (experience as string).trim();
  const cleanWhy   = (why as string).trim();
  const cleanSystem = (system as string).trim();

  let riskScore = 0;
  const riskFlags: string[] = [];

  // 1. Disposable / burner email domains
  const DISPOSABLE_DOMAINS = new Set([
    "mailinator.com", "guerrillamail.com", "temp-mail.org", "throwam.com",
    "yopmail.com", "trashmail.com", "sharklasers.com", "guerrillamailblock.com",
    "10minutemail.com", "maildrop.cc", "fakeinbox.com", "dispostable.com",
  ]);
  const emailDomain = cleanEmail.split("@")[1] ?? "";
  if (DISPOSABLE_DOMAINS.has(emailDomain)) {
    riskScore += 35;
    riskFlags.push("disposable_email");
  }

  // 2. Very short answers — low effort
  if (cleanExp.length < 80) { riskScore += 15; riskFlags.push("short_experience"); }
  if (cleanWhy.length < 40) { riskScore += 10; riskFlags.push("short_why"); }
  if (cleanSystem.length < 60) { riskScore += 10; riskFlags.push("short_system_built"); }

  // 3. Duplicate email (same person re-applying)
  const { count: dupeCount } = await supabaseAdmin
    .from("applications")
    .select("id", { count: "exact", head: true })
    .eq("email", cleanEmail);
  if ((dupeCount ?? 0) > 0) {
    riskScore += 25;
    riskFlags.push("duplicate_email");
  }

  // 4. Duplicate IP (multiple apps from same IP)
  const { count: ipCount } = await supabaseAdmin
    .from("applications")
    .select("id", { count: "exact", head: true })
    .eq("ip_address", ip);
  if ((ipCount ?? 0) >= 2) {
    riskScore += 20;
    riskFlags.push("multiple_from_ip");
  }

  // Cap at 100
  const finalRiskScore = Math.min(riskScore, 100);

  // ── Persist ──────────────────────────────────────────────────────────────
  const { error: dbError } = await supabaseAdmin.from("applications").insert({
    name: (name as string).trim(),
    email: cleanEmail,
    phone: (phone as string).trim(),
    authorized: (authorized as string).trim(),
    sponsorship: (sponsorship as string).trim(),
    role: (role as string).trim(),
    salary: typeof salary === "string" && (salary as string).trim() ? (salary as string).trim() : null,
    start_date: typeof start_date === "string" && (start_date as string).trim() ? (start_date as string).trim() : null,
    years_experience: typeof years === "string" && (years as string).trim() ? (years as string).trim() : null,
    experience: (experience as string).trim(),
    system_built: (system as string).trim(),
    why: (why as string).trim(),
    felony: (felony as string).trim(),
    felony_explain:
      (felony as string).trim() === "yes" && typeof felony_explain === "string" && (felony_explain as string).trim()
        ? (felony_explain as string).trim()
        : null,
    portfolio: typeof portfolio === "string" && (portfolio as string).trim() ? (portfolio as string).trim() : null,
    linkedin: typeof linkedin === "string" && (linkedin as string).trim() ? (linkedin as string).trim() : null,
    professional_references: typeof references === "string" && (references as string).trim() ? (references as string).trim() : null,
    school: typeof school === "string" && (school as string).trim() ? (school as string).trim() : null,
    degree: typeof degree === "string" && (degree as string).trim() ? (degree as string).trim() : null,
    discipline: typeof discipline === "string" && (discipline as string).trim() ? (discipline as string).trim() : null,
    additional_profiles: typeof additional_profiles === "string" && (additional_profiles as string).trim() ? (additional_profiles as string).trim() : null,
    why_role: (why_role as string).trim(),
    company_mission: (company_mission as string).trim(),
    previously_employed: typeof previously_employed === "string" && previously_employed.trim() ? previously_employed.trim() : null,
    employment_dates:
      typeof previously_employed === "string" && previously_employed.trim() === "yes" &&
      typeof employment_dates === "string" && (employment_dates as string).trim()
        ? (employment_dates as string).trim() : null,
    contract_work: typeof contract_work === "string" && contract_work.trim() ? contract_work.trim() : null,
    contract_details:
      typeof contract_work === "string" && contract_work.trim() === "yes" &&
      typeof contract_details === "string" && (contract_details as string).trim()
        ? (contract_details as string).trim() : null,
    resume_url: (resume_url as string).trim(),
    cover_letter_url: typeof cover_letter_url === "string" && cover_letter_url.trim() ? cover_letter_url.trim() : null,
    agree: true,
    ip_address: ip,
    risk_score: finalRiskScore,
    risk_flags: riskFlags.length > 0 ? riskFlags : null,
  });

  if (dbError) {
    console.error("careers apply insert error:", dbError.message);
    return NextResponse.json(
      { error: "An error occurred. Please try again." },
      { status: 500 }
    );
  }

  // Send confirmation email to applicant (fire-and-forget, don't block response)
  sendConfirmationEmail(
    (email as string).trim(),
    (name as string).trim(),
    (role as string).trim(),
  ).catch((err) => console.error("careers confirmation email error:", err));

  return NextResponse.json({ ok: true }, { status: 201 });
}

function escHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

async function sendConfirmationEmail(toEmail: string, name: string, role: string) {
  const from = process.env.EMAIL_FROM || "1neLink <noreply@1nelink.com>";
  const firstName = escHtml(name.split(" ")[0]);
  const safeRole  = escHtml(role);

  const html = `
    <div style="font-family:sans-serif;background:#050A1A;padding:40px 24px;">
      <div style="max-width:540px;margin:0 auto;background:#0D1426;border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:40px;">

        <div style="margin-bottom:28px;">
          <div style="font-size:22px;font-weight:700;color:#ffffff;margin-bottom:4px;">1neLink</div>
          <div style="width:40px;height:3px;background:#3B82F6;border-radius:2px;"></div>
        </div>

        <h2 style="font-size:20px;font-weight:700;color:#fff;margin:0 0 20px;">Application Received</h2>

        <p style="font-size:15px;color:#e5e7eb;margin:0 0 16px;">Hi ${firstName},</p>
        <p style="font-size:15px;color:#e5e7eb;line-height:1.6;margin:0 0 16px;">
          Thank you for applying for the <strong style="color:#ffffff;">${safeRole}</strong> position at 1neLink.
          Your application has been received and is in our review queue.
        </p>
        <p style="font-size:15px;color:#e5e7eb;line-height:1.6;margin:0 0 28px;">
          We review every application manually and aim to respond within <strong style="color:#fff;">5&ndash;7 business days</strong>.
          You don&#39;t need to do anything else at this time.
        </p>

        <div style="background:rgba(59,130,246,0.08);border:1px solid rgba(59,130,246,0.2);border-radius:10px;padding:16px;margin-bottom:28px;">
          <p style="margin:0;font-size:13px;color:#93c5fd;">
            <strong>Role applied:</strong> ${safeRole}<br/>
            <strong>Status:</strong> Under review
          </p>
        </div>

        <p style="font-size:13px;color:#6b7280;margin:0;">
          Best regards,<br/><strong style="color:#e5e7eb;">The 1neLink Hiring Team</strong>
        </p>
        ${emailFooter()}
      </div>
    </div>
  `;

  const resend = getResend();
  await resend.emails.send({
    from,
    to: toEmail,
    subject: `Application Received – ${role} at 1neLink`,
    html,
  });
}
