import Stripe from "stripe";

export type StripeWebhookEvent =
  | (Stripe.Event & { type: "payment_intent.succeeded"; data: { object: Stripe.PaymentIntent } })
  | (Stripe.Event & { type: "payment_intent.payment_failed"; data: { object: Stripe.PaymentIntent } })
  | (Stripe.Event & { type: "payment_intent.canceled"; data: { object: Stripe.PaymentIntent } })
  | (Stripe.Event & { type: "charge.refunded"; data: { object: Stripe.Charge } })
  | (Stripe.Event & { type: "refund.created"; data: { object: Stripe.Refund } })
  | (Stripe.Event & { type: "charge.dispute.created"; data: { object: Stripe.Dispute } })
  | (Stripe.Event & { type: "charge.dispute.updated"; data: { object: Stripe.Dispute } })
  | (Stripe.Event & { type: "charge.dispute.closed"; data: { object: Stripe.Dispute } })
  | (Stripe.Event & { type: "payout.paid"; data: { object: Stripe.Payout } })
  | (Stripe.Event & { type: "payout.failed"; data: { object: Stripe.Payout } })
  | (Stripe.Event & { type: "account.updated"; data: { object: Stripe.Account } })
  | (Stripe.Event & { type: "account.application.deauthorized"; data: { object: Stripe.Account } })
  | (Stripe.Event & { type: "account.external_account.updated"; data: { object: Stripe.BankAccount | Stripe.Card } })
  | (Stripe.Event & { type: "capability.updated"; data: { object: Stripe.Capability } })
  | (Stripe.Event & { type: "person.updated"; data: { object: Stripe.Person } })
  | (Stripe.Event & { type: "review.opened"; data: { object: Stripe.Review } })
  | (Stripe.Event & { type: "review.closed"; data: { object: Stripe.Review } })
  | (Stripe.Event & { type: "transfer.created"; data: { object: Stripe.Transfer } })
  | (Stripe.Event & { type: "transfer.updated"; data: { object: Stripe.Transfer } })
  | (Stripe.Event & { type: "transfer.reversed"; data: { object: Stripe.TransferReversal | Stripe.Transfer } })
  | (Stripe.Event & { type: "issuing_authorization.request"; data: { object: Stripe.Issuing.Authorization } })
  | (Stripe.Event & { type: "issuing_authorization.created"; data: { object: Stripe.Issuing.Authorization } })
  | (Stripe.Event & { type: "issuing_authorization.updated"; data: { object: Stripe.Issuing.Authorization } })
  | (Stripe.Event & { type: "issuing_authorization.declined"; data: { object: Stripe.Issuing.Authorization } })
  | (Stripe.Event & { type: "issuing_transaction.created"; data: { object: Stripe.Issuing.Transaction } })
  | (Stripe.Event & { type: "issuing_transaction.updated"; data: { object: Stripe.Issuing.Transaction } })
  | (Stripe.Event & { type: "issuing_card.updated"; data: { object: Stripe.Issuing.Card } })
  | (Stripe.Event & { type: "issuing_cardholder.updated"; data: { object: Stripe.Issuing.Cardholder } })
  | (Stripe.Event & { type: "issuing_dispute.created"; data: { object: Stripe.Issuing.Dispute } })
  | (Stripe.Event & { type: "issuing_dispute.closed"; data: { object: Stripe.Issuing.Dispute } })
  | (Stripe.Event & { type: "checkout.session.completed"; data: { object: Stripe.Checkout.Session } })
  | (Stripe.Event & { type: "customer.subscription.deleted"; data: { object: Stripe.Subscription } })
  | (Stripe.Event & { type: "customer.subscription.updated"; data: { object: Stripe.Subscription } })
  | (Stripe.Event & { type: "invoice.payment_succeeded"; data: { object: Stripe.Invoice } })
  | (Stripe.Event & { type: "invoice.payment_failed"; data: { object: Stripe.Invoice } });

export default StripeWebhookEvent;
