import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ui } from "@/lib/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className={ui.page}>
          <div className={ui.glowWrap}>
            <div className={ui.glow1} />
            <div className={ui.glow2} />
            <div className={ui.glow3} />
            <div className={ui.topLine} />
          </div>

          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
