/**
 * Alert: Email — sends a security alert email to the configured address.
 */

import { sendEmailAsync } from "@/lib/emailService";
import { securityConfig } from "../config/security-config";
import type { SecurityAlert } from "../types/security-event";
import { createLogger } from "../utils/logger";

const log = createLogger("alert-email");

export function sendEmailAlert(alert: SecurityAlert): void {
  const to = securityConfig.alerts.email;
  if (!to) {
    log.warn("SECURITY_ALERT_EMAIL not set — skipping email alert");
    return;
  }

  const severityEmoji: Record<string, string> = {
    CRITICAL: "🚨",
    HIGH: "⚠️",
    MEDIUM: "🔔",
    LOW: "ℹ️",
  };

  const icon = severityEmoji[alert.severity] ?? "🔔";

  sendEmailAsync({
    type: "NOTIFICATION",
    to,
    subject: `${icon} [${alert.severity}] Security Alert — ${alert.type}`,
    html: `
      <div style="font-family:sans-serif;max-width:600px;">
        <h2 style="color:#dc2626;">${icon} Security Alert: ${alert.type}</h2>
        <p><strong>Severity:</strong> ${alert.severity}</p>
        <p><strong>Summary:</strong> ${alert.summary}</p>
        ${alert.ipMasked ? `<p><strong>Source IP (masked):</strong> ${alert.ipMasked}</p>` : ""}
        ${
          Array.isArray(alert.playbook) && alert.playbook.length > 0
            ? `<h3>Recommended Actions:</h3><ol>${(alert.playbook as string[]).map((s) => `<li>${s}</li>`).join("")}</ol>`
            : ""
        }
        <p style="color:#6b7280;font-size:12px;">Generated by 1neLink Security Monitor</p>
      </div>
    `,
  });

  log.info("Email alert sent", { type: alert.type, severity: alert.severity });
}
